
def fastnbs(question:str, accu:float=0.8, n=10, nb=False, db=False):======================(0)       
    "using keywords to search learning points from my documented fastai notebooks"========(1)       
    questlst = question.split(' ')========================================================(2)       
    folder ='/Users/Natsume/Documents/divefastai/Debuggable/jupytext/2022part1/'==========(3)       
    for f in os.listdir(folder):  ========================================================(4)       
        if f.endswith(".md"):=============================================================(5)       
            if db: print(f'pct: {pct}')===================================================(6)       
            file_name =folder + f=========================================================(7)       
            with open(file_name, 'r') as file:============================================(8)       
                for l in file:============================================================(9)       
                    truelst = [q in l for q in questlst]==================================(10)      
                    pct = sum(truelst)/len(truelst)=======================================(11)      
                                                                                                                                                        (12)
                    if pct >= accu:=======================================================(13)      
                        head1 = f"keyword match is {pct}, Found a line: in {f}"===========(14)      
                        head1 = highlight(str(pct), head1)================================(15)      
                        head1 = highlight(f, head1)=======================================(16)      
                        display_md(head1)=================================================(17)      
                        print(l, end='')==================================================(18)      
                        print()===========================================================(19)      
                                                                                                                                                        (20)
                        head2 = f"Show {n} lines after in {f}:"===========================(21)      
                        head2 = highlight(f, head2)=======================================(22)      
                        head2 = highlight(str(n), head2)==================================(23)      
                        display_md(head2)                        =========================(24)      
                        idx = count=======================================================(25)      
                        with open(file_name, 'r') as file:================================(26)      
                            for count, l in enumerate(file):==============================(27)      
                                if count >= idx and count <= idx + n:=====================(28)      
                                    if count == idx: display_md(highlight(question, l))===(29)      
                                    else: display_md(l)                        ===========(30)      
                        if nb:============================================================(31)      
                            openNB(f, "nbs/2022part1/")===================================(32)      
                                                                                                                                                        (33)
