def create_snoop_from_string(self:Fastdb, db=False):======================================(0)       
    # learn about /tmp folder https://www.fosslinux.com/41739/linux-tmp-directory-everything-you-need-to-know.htm                                       (1)
    file_name ='/tmp/' + self.orisrc.__name__ + '.py' ====================================(2)       
    with open(file_name, 'w') as f:=======================================================(3)       
        f.write(self.dbsrcstr)============================================================(4)       
    code = compile(self.dbsrcstr, file_name, 'exec')======================================(5)       
#             exec(dbsrc, locals(), self.egEnv)                ===========================(6)       
#     exec(code, globals().update(self.outenv), locals()) # when dbsrc is a method, it will update as part of a class                                   (7)
    exec(code, globals().update(self.outenv)) # when dbsrc is a method, it will update as part of a class                                               (8)
    # store dbsrc func inside Fastdb obj==================================================(9)       
    self.dbsrc = locals()[self.orisrc.__name__]===========================================(10)      
                                                                                                                                                        (11)
