# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/lib/groundup_004_forward_backward_passes.ipynb.

# %% auto 0
__all__ = ['a']

# %% ../nbs/lib/groundup_004_forward_backward_passes.ipynb 3
a = "to delete"
