# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/fastai_notebooks/0001_fastai_is_it_a_bird.ipynb.

# %% auto 0
__all__ = ['Learner']

# %% ../nbs/fastai_notebooks/0001_fastai_is_it_a_bird.ipynb 191
from fastcore.basics import patch
from fastai.learner import GetAttr
from .utils import *

# %% ../nbs/fastai_notebooks/0001_fastai_is_it_a_bird.ipynb 197
class Learner(GetAttr): pass

# %% ../nbs/fastai_notebooks/0001_fastai_is_it_a_bird.ipynb 198
@patch
@snoop
def predict(self:Learner, item, rm_type_tfms=None, with_input=False):
    pp(doc_sig(self.dls.test_dl))
    dl = self.dls.test_dl([item], rm_type_tfms=rm_type_tfms, num_workers=0)
    pp(doc_sig(self.get_preds))
    inp,preds,_,dec_preds = self.get_preds(dl=dl, with_input=True, with_decoded=True)
    i = getattr(self.dls, 'n_inp', -1)
    if i==1:
        inp = (inp,) 
    else:
        inp = tuplify(inp)
    pp(doc_sig(self.dls.decode_batch))
    dec = self.dls.decode_batch(inp + tuplify(dec_preds))[0]
    pp(doc_sig(tuplify), doc_sig(detuplify))
    dec_inp,dec_targ = map(detuplify, [dec[:i],dec[i:]])
    res = dec_targ,dec_preds[0],preds[0]
    if with_input: 
        res = (dec_inp,) + res
    return res
# File:      ~/mambaforge/lib/python3.9/site-packages/fastai/learner.py
# Type:      method
