# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/lib/fastai_from_scratch/0000_fastscratch_export.ipynb.

# %% auto 0
__all__ = ['TEST']

# %% ../nbs/lib/fastai_from_scratch/0000_fastscratch_export.ipynb 2
TEST = "test"
