# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/fastai_notebooks/0012_fastai_using_nbdev_export_in_kaggle_notebook.ipynb.

# %% auto 0
__all__ = ['a']

# %% ../nbs/fastai_notebooks/0012_fastai_using_nbdev_export_in_kaggle_notebook.ipynb 8
a=1
